name: Build .NET 5 projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        targetplatform: [x64]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET5 workload
    - name: Install .NET5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build Config
      run: dotnet build ./config/Config.csproj --configuration Release --framework net5.0-windows --output ./x64/Release

    - name: Build Toolkit
      run: dotnet build ./src/SimpleDICOMToolkit.csproj --configuration Release --framework net5.0-windows --output ./x64/Release
